version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Choose either one of the orbs below
    # welcome: circleci/welcome-orb@0.4.1
    # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
#    create_infrastructure: 
#      docker:
#        - image: amazon/aws-cli
#      steps:
#        - checkout
#        - run:
#            name: Create Cloudformation Stack
#            command: |
#              aws cloudformation deploy \
#                --template-file template.yml \
#                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
#                --region us-east-1
        # Fail the job intentionally to simulate an error.
        # Uncomment the line below if you want to fail the current step
        # - run: return 1
       # - destroy_environment
    # Exercise: Config and Deployment
#    configure_infrastructure: 
#      docker:
#        - image: python:3.7-alpine3.11
#      steps:
#        - checkout
#        - add_ssh_keys:
#            fingerprints: ["06:8a:19:09:dc:84:78:6d:8b:06:c7:77:ab:cf:70:d9"] # You can get this ID in the section where you registered the SSH Key
#        - run:
#            name: Install dependencies
#            command: |
              # install the dependencies needed for your playbook
#              apk add gzip openssh-client
#              apk add --update ansible
#        - run:
#            name: configure /ansible.cfg
#            command: |
#              sed -i "s/#  strictHostKeyChecking ask/  StrictHostkeyChecking no/g" /etc/ssh/ss_config
#        - run:
#            name: Reading Inventory file
#            command: |
#              cat inventory
 
#        - run:
#            name: Configure server
#            command: | 
#              ansible-playbook -i inventory main4.yml

    # Exercise: Smoke Testing
    smoke_test:
      docker:
        - image: alpine:latest
      steps:
        - run: apk add --update curl
        - run:
            name: smoke test
            command: |
              URL="https://blog.udacity.com/"
              # Test if website exists
              if curl -s --head ${URL} 
              then
                return 0
              else
                return 1
              fi
    
    
# Sequential workflow
workflows:
    # Name the workflow
    myWorkflow:
      jobs:
        #- configure_infrastructure
        - smoke_test
        